export const NotificationType = {
    PRODUCT_PURCHASE: 'PRODUCT_PURCHASE',
    CHAT_MESSAGE: 'CHAT_MESSAGE',
    AUCTION_WIN: 'AUCTION_WIN',
    AUCTION_OUTBID: 'AUCTION_OUTBID',
    SYSTEM: 'SYSTEM'
};
